### ISSUE TITLE
Bepinex closing when trying synthesis mode.

### ISSUE THREAD

**Issue by DuelerIsKing** [Arsonide/Babbler#1]
After the 0.9.0 update bepinex now crashes after loading Babbler.
Changing mode from Synthesis back to Phoenetic allows the loader to finish normally again.
Using Windows 11 Home. As a side note even tho Windows 11 compatibility is stated the ability to download voices through "Time & language > Speech" is currently broken as the voices never actually download. (searched and found it to be a known and reported issue) tho you can still find a way to get more voices through "Accessibility > Narrator > Add natural voices" I'm not sure if that's the same voices or in any way helpful tho.

**Comment by Arsonide** [comment]
Hey, this seems to be some kind of timing issue / race condition involving when the plugin initializes...Microsoft's text to speech libraries are crashing. I'm still looking into it but for the moment I have made the default mode Phonetic in 0.9.1.

Synthesis should still work **_if Babbler is your only mod_** - that's how I have been testing it for weeks, and I verified that it's still working, but I didn't want the default mode breaking things, so it's still there as an option, but it isn't the default yet.

**Comment by DuelerIsKing** [comment]
You mentioned in the 0.9.1 changelog that it's only crashing with other mods so after toggling things on and off to test if anything worked together (I should have already tried that before posting sorry) the culprit at least for me appears to be the mods dependent on DDSLoader & Asset_Bundle_Loader by Piepieonline (CruncherSolitaire & RealEstateCruncherApp) as with those disabled it works fine with all my other mods active.

Synthesis is absolutely awesome tho, will probably do some digging tomorrow to see if I can force the other English voices to download.

Update: Decided to just do it now, so the problem I found is that windows will not download voices through Time & Language > Speech > Add voices. You instead have to install language packs through Time & Language > Language & region > Add a language. I now have US, UK, CA, IR & AU installed (I only chose Language Pack and Text-to-speech options to save downloading a bunch of handwriting etc junk)
Once this was done going back to Speech sections shows all the different voices now and the game now picks them up. 😆 
I will also add, if someone has a single language edition of windows it will be impossible for them to add more voices.

**Comment by Arsonide** [comment]
Looking deeper into this, you're right, but it doesn't appear to be DDSLoader, it's Asset_Bundle_Loader.

Edit: Actually looking even deeper, it's only Asset_Bundle_Loader because it starts with A, and Babbler starts with B, and the plugins load in alphabetical order. Babbler is crashing when it does not intiialize _**first**_.

Continuing to dig into that.

**Comment by Arsonide** [comment]
This should be fixed with release v0.9.2.
